
[tool.poetry]
name = "load-generator-python"
version = "0.1.0"
description = ""
authors = ["Vickouma77"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.4"

[poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"