load('ext://ko', 'ko_build')
ko_build(
  'vickouma/infra-ops-api-golang', 
  './',
  deps=['.']
)
k8s_yaml('../../deploying-demo-app/api-golang/Deployment.yaml')
k8s_resource('api-golang', port_forwards=8000)